### ISSUE TITLE
Support osc release feature in obs service

### ISSUE THREAD

**Issue by schaefi** [SUSE-Enceladus/mash#217]
The obs service downloads the image build from a given project. This requires an account in the build service used for the mash use case and also a role setup for that account in the projects handled by the obs service

A better solution to the account problem could be to use the osc release feature. See the following excerpt from a conversation by mail which summarizes the idea

```
OK, from my point of view we have our answer, publish into a separate
project and get the binaries refreshed with "osc release". According to
the mail thread with Adrian that should afford us a credential less
access to the binaries and the project does not need a new generic role
associated with it.

Of course this requires a bunch of changes in the obs service and it
requires some preliminary work as well. I have a hard time believing the
"osc release" can be run without credentials. Thus this should be tested
first before any code changes are made.

If that works the obs service would instead of locking the package, run
"osc release" and then pick up the package from the alternate release area.

The upside is that we do not have to handle credentials for OBS at all
and any user that wants to use mash can configure their OBS project with
a couple of lines of metadata.
```

**Comment by smarlowucf** [comment]
Instead of OSC release we can get (wget/curl).

E.g.

- Use the wget/curl to get index page for images (http://download.suse.de/ibs/Devel:/PubCloud:/Stable:/Images12/images/)
- Parse the build number and image size
- Pull and check conditions with packages file
- If conditions are met then make sure the build number and size still match and pull image.

Note: The name of image as it is in the kiwi file must be in job description.

**Comment by schaefi** [comment]
@smarlowucf thanks for the notes. I'll take this one next
