### ISSUE TITLE
Uploader service relies on cloud image name from job creator

### ISSUE THREAD

**Issue by smarlowucf** [SUSE-Enceladus/mash#278]
Instead of generating the names based on date.

Uploader service should instead expect a template based name that a date is added when image is uploaded.

E.g. cloud_image_name == 'suse-sles-11-sp4-v{date}-hvm-ssd-x86_64'

Then uploader would format with proper date and use like:

`'suse-sles-11-sp4-v{date}-hvm-ssd-x86_64'.format('20180907')`

**Comment by schaefi** [comment]
I'm not so sure why the uploader should support a template for the image name. imho the job description should be as explicit as ever possible. If the cloud_image_name is not a fixed information it's imho hard to identify what exactly the job has done or will do

**Comment by smarlowucf** [comment]
I thought we had agreed on this? Since a job with conditions could be submitted any number of days prior to the image being uploaded. This would allow uploader service to append the proper date to the name.

**Comment by schaefi** [comment]
I'm sorry I can't remember that this was discussed, probably my old brain.

At the time the job creator service constructs the jobs it knows when the uploader job should run the upload right ? I mean this is an information which gets passed to the job creator from some user input. It would be no problem for the job creator to create the cloud_image_name from that information.

If we just construct the utctime information in the uploader job and replace the date at call time in the uploader code it will result in the same  cloud_image_name but it feels odd to me why we don't follow the explicit is better than implicit workflow. The job creator service has to cope with the date anyway in order to construct the correct utctime value for the uploader job, it could use the same information for cloud_image_name and keep the uploader service free from any data calculations, or am I mistaken ?

**Comment by smarlowucf** [comment]
> At the time the job creator service constructs the jobs it knows when the uploader job should run the upload right ?

Right, although it's not guaranteed that the image is uploaded and published the same day it's triggered. Probably not a big deal though.

> It would be no problem for the job creator to create the cloud_image_name from that information.

That's true, could be done in job creator.

> The job creator service has to cope with the date anyway in order to construct the correct utctime value for the uploader job

Not necessarily. `utctime` is passed in by the user the services just parse it and OBS is the only service that directly acts on it.

Either way this is mainly an enhancement I think at this point so I added the target #2.

**Comment by rjschwei** [comment]
We will need this functionality, good catch @smarlowucf.

Here is the example that goes along with it. Let's say the next CPU side channel attack is known and has a known embargo date. Then we know the earliest time we can release. However, we do not know when the kernel with mitigation is going to be available. But we do know the kernel version with the fix ahead of time.

Part of the goal of mash for our use case was/is to remove people from the "constant" monitoring of build projects in these cases.

In this case a user would submit a job with a condition kernel X.Y.Z. The uploader will monitor the condition and pull and push the image. However the pull (from build service) - push (to cloud framework) operation could be today 20180918, or tomorrow (20180919) or some time after, depending on when the maintenance team releases the fixed kernel. The date of the image has to match the upload date, this is a must have condition.

**Comment by schaefi** [comment]
> The date of the image has to match the upload date, this is a must have condition.

ok
