### ISSUE TITLE
VPC not cleaned up

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#414]
After uploading to an account in AWS with mash the mash created VPC is left behind.

uploader-41

remained in the account. This may be related to the failure path, as the job failed with 

"Pass[1]: Error: MashImageDownloadException: Build number mismatch between me
tadata and image files"

**Comment by rjschwei** [comment]
This may also be related to a test instance being left behind.

**Comment by smarlowucf** [comment]
This is confusing. The `MashImageDownloadException` occurs in build_result which is part of OBS service. So that job would never have made it to Uploader or Testing both of which create temporary VPCs.

The VPC must have been left behind by something other job or some other action. There was a case where the Testing service would leave behind an instance and/or VPC when exception occured but this was fixed in https://github.com/SUSE-Enceladus/mash/commit/6f77cbadd122c86e31dfbb5ad9f76908fe32e6a8 and released with v2.1.0.

**Comment by smarlowucf** [comment]
Also if an instance was left running then that would be a bug in IPA.

**Comment by smarlowucf** [comment]
To my knowledge this issue has not shown up recently so will close for now. If this happens again we will need to pinpoint the location of failure.
