### ISSUE TITLE
image not cleaned up

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#462]
When testing failes in GCE the image needs to be removed if we are in a public project. Presumably the test failure indicates that the image is not usable. Since there is no specific switch in Google to make the image public, rather the image is public based on the project, the image needs to be removed if the tests fail.

**Comment by smarlowucf** [comment]
This workflow hints on cleanup being triggered by testing service. Because it can happen in different services for each cloud it seems the best option is have a cleanup module rather than another out of pipeline service.

Also, from running tests I noticed that when you upload a new version of an existing image family the recent image gets deprecated automagically. This will need to be undone during cleanup.

**Comment by rjschwei** [comment]
Uploading a new image does not automatically deprecate the previous image. For example:
```
gcloud compute images list --project suse-cloud --show-deprecated --no-standard-images
NAME                   PROJECT     FAMILY   DEPRECATED  STATUS
sles-11-sp4-v20180816  suse-cloud  sles-11  DEPRECATED  READY
sles-12-sp3-v20180814  suse-cloud  sles-12  DEPRECATED  READY
sles-12-sp4-v20181212  suse-cloud  sles-12  DEPRECATED  READY
sles-12-sp4-v20190221  suse-cloud  sles-12              READY
sles-12-sp4-v20190520  suse-cloud  sles-12              READY
sles-15-v20180816      suse-cloud  sles-15  DEPRECATED  READY
sles-15-v20190221      suse-cloud  sles-15  DEPRECATED  READY
sles-15-v20190520      suse-cloud  sles-15              READY
```

Shows that there are multiple sles-12-sp4 images that are not deprecated. Uploading a new image to a family basically resets the "latest" pointer. Meaning a user using the family to launch an instance always runs the latest image. When the new image is deleted and as long as the previous image is still active, i.e. not marked as `DEPRECATED` the logic reverts as could be expected.
