### ISSUE TITLE
retry on replication failure in EC2

### ISSUE THREAD

**Issue by rjschwei** [SUSE-Enceladus/mash#503]
When replication fails to a given region we should try again.

```
ERROR 2019-08-02 19:51:34,751 ReplicationService
     Pass[1]: There was an error replicating image to eu-north-1. Waiter ImageAvailable failed: Max attempts exceeded

ERROR 2019-08-02 20:01:31,311 ReplicationService
     Pass[1]: There was an error replicating image to ap-northeast-3. Waiter ImageAvailable failed: Max attempts exceeded

INFO 2019-08-02 20:01:31,720 ReplicationService
     Deleting job.

ERROR 2019-08-02 20:01:31,720 ReplicationService
     Pass[1]: Error occurred in replication.

WARNING 2019-08-02 20:01:31,722 PublisherService
     Failed upstream.

INFO 2019-08-02 20:01:31,723 PublisherService
     Deleting job.
```

**Comment by smarlowucf** [comment]
This is not a failure, it's a timeout. There are two waits in place so a retry is an over complication. A retry 3 times on a waiter that waits 5 minutes is the same as a waiter that waits 15 minutes and the latter is much simpler.

**Comment by smarlowucf** [comment]
The initial wait can be bumped to 15 minutes in the ec2 replication job class and we can update the waiter timeout based on the following example:

```
waiter.wait(
    Filters=[
        {
            'Name': 'string',
            'Values': [
                'string',
            ]
        },
    ],
    InstanceIds=[
        'string',
    ],
    DryRun=True|False,
    MaxResults=123,
    NextToken='string',
    WaiterConfig={
        'Delay': 123,
        'MaxAttempts': 123
    }
)
```

The default wait is only a total of 200 seconds (Delay: 5, MaxAttempts: 40).

**Comment by rjschwei** [comment]
Sorry, I didn't dig into the code before filing the issue, then again I am not certain that is my responsibility as an issue creator.

Anyway, given that the replication operation has started we should just basically wait forever with the assumption that the platform will eventually finish.

**Comment by smarlowucf** [comment]
Agree with bumping the wait period. The failure took about double the expected (10-15 minutes) time. I think we should not overreact to failure and should have some sort of expectation from the framework in use. If the period is bumped to multiple hours we catch the vast majority if not all replications. If any region fails to meet the expectations consistently then maybe this is something that we want to know about and relay the issues upstream.

If the wait is bumped to an "almost forever" time frame then if something causes a region to get stuck in replication this means a job could be stuck for many days. It won't be until a developer goes in and figures out the issue, cancels the job anyway and manually pushes the job along will the publishing finish.

There's also the consideration of limits:

`Destination Regions are limited to 50 concurrent AMI copies.`

There is no information on how the platform handles this if it occurs. Whether it is handled with throttling or explicit failure when limits reached. However, unless/until this becomes an issue I think this should only be made aware of rather than trying to account for an unknown.

**Comment by rjschwei** [comment]
We should add the replication time to the logs, then we can collect statistics. Generally I agree it would be good to make the provider aware of the issue. But we should not expect to do that manually. The later would imply a configuration option to configure a framework provider e-mail and a pre-defined template with the e-mail text.

The bottom line is that we are trying to simulate what a person would do, and that is:
- issue copy-image command
- wait until the copy is completed
- if it takes too long go complain to someone
